# Generated by Django 5.0.2 on 2024-02-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_createjobposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='createjobposts',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
