# Generated by Django 5.0.2 on 2024-02-13 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.profile'),
        ),
        migrations.AddField(
            model_name='createjobposts',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.profile'),
        ),
    ]
