# Generated by Django 5.0.2 on 2024-02-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_applyjob_user_profile_createjobposts_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='createjobposts',
            name='user_profile',
        ),
    ]
